AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/support/**/*'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  AllowURI: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  Enabled: false
