AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'spec/support/**/*'

ClassLength:
  Max: 300

LineLength:
  Max: 128

MethodLength:
  Max: 40

Encoding:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: False

Style/StringLiterals:
  Enabled: false
